### ISSUE TITLE
Make an app icon

### ISSUE THREAD

**Issue by cannam** [yucongj/piano-precision#17]
Piano Precision needs an icon! At the moment it is just using the SV one.

A way to approach it might be to edit the [Sonic Visualiser icon SVG outline](https://github.com/yucongj/piano-precision/blob/main/icons/sv-icon.svg) using Inkscape or similar, perhaps producing something with the same general design, i.e. a coloured box with some topical outline inside.

(Conversion from SVG to whatever other formats we might need is something I can handle easily enough.)

For reference, the icons for SV and its related applications Tony and Sonic Lineup are:

![sv-icon](https://github.com/yucongj/piano-precision/assets/104933/8762e755-e659-4e75-8af3-874ef3b89cfe)
![tony-icon](https://github.com/yucongj/piano-precision/assets/104933/280414bf-bb88-43c8-8a3c-b64107f11dec)
![sonic-lineup-icon](https://github.com/yucongj/piano-precision/assets/104933/14aa084f-c2b6-4d24-9937-53b3cb37cd24)

**Comment by yucongj** [comment]
Here's the SVG version of the icon:
![piano-precision-icon](https://github.com/yucongj/piano-precision/assets/60488433/62b238a0-6be3-4774-8f78-12d427959aa4)
